kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build and push
    image: plugins/kaniko
    settings:
      repo: registry.local:5000/p2p/drone-test
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
      cache: true
      skip_tls_verify: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - main
