kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: gcr.io/kaniko-project/executor:v1.9.0-debug
    commands:
      - /kaniko/executor --verbosity debug -f `pwd`/Dockerfile -c `pwd` --insecure --skip-tls-verify --cache=true --destination=docker.io/524c/kaniko-test:latest

  - name: push
    image: plugins/docker
    settings:
      repo: "p2p/drone-test"
      registry: registry.cluster
      insecure: true
      #username:
      #  from_secret: docker_username
      #password:
      #  from_secret: docker_password
    when:
      event:
        include:
          - push

trigger:
  branch:
    - main
