kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: plugins/kaniko

    settings:
      repo: registry.cluster:5000/524c/drone-test
      #tags: latest
      tags: ${DRONE_COMMIT_SHA}
      cache: true
      skip_tls_verify: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: push
    image: plugins/docker
    settings:
      repo: "p2p/drone-test"
      registry: registry.cluster
      insecure: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      #username:
      #  from_secret: docker_username
      #password:
      #  from_secret: docker_password

trigger:
  branch:
    - main
