kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: gcr.io/kaniko-project/executor:latest
    settings:
      repo: "p2p/drone-test"
    commands:
      - /kaniko/executor --context ${{ clone.payload }} --dockerfile ${{ clone.payload }}/Dockerfile --destination ${{ plugin.settings.repo }} --cache=true

  - name: push
    image: plugins/docker
    settings:
      repo: "p2p/drone-test"
      registry: registry.cluster
      insecure: true
      #username:
      #  from_secret: docker_username
      #password:
      #  from_secret: docker_password
    when:
      event:
        include:
          - push

trigger:
  branch:
    - main
