kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: plugins/kaniko
    environment:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    settings:
      repo: docker.io/524c/drone-test
      tags: latest

  - name: push
    image: plugins/docker
    settings:
      repo: "p2p/drone-test"
      registry: registry.cluster
      insecure: true
      #username:
      #  from_secret: docker_username
      #password:
      #  from_secret: docker_password
    when:
      event:
        include:
          - push

trigger:
  branch:
    - main
