kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

# use custom dns server

steps:
  - name: kaniko
    image: plugins/kaniko
    settings:
      username: roger
      password: pa55word
      repo: "registry.cluster:5000/p2p/drone-test"
      tags:
        - ${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_COMMIT_BRANCH}
      insecure: true

  - name: push
    image: plugins/docker
    settings:
      repo: "p2p/drone-test"
      registry: registry.cluster:5000
      insecure: true
      #username:
      #  from_secret: docker_username
      #password:
      #  from_secret: docker_password
    when:
      event:
        include:
          - push

trigger:
  branch:
    - main
